version: '3'
services:
  mocorona-api:
    container_name: mocorona_api
    build: .
    ports:
      - 8001:8001
    restart: always
    volumes:
      - mocorona_api:/usr/src/app/
    depends_on:
      - mocorona-postgres
    networks:
      - mocorona
    environment:
      - DB_HOST=mocorona_postgres


  mocorona-postgres:
    image: postgres:latest
    container_name: mocorona_postgres
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - mocorona_postgres:/var/lib/postgresql/data
    networks:
      - mocorona

volumes:
  mocorona_api:
  mocorona_postgres:

networks:
  mocorona:
    driver: bridge
